name: Deploy v2.mygifts.me

on:
  push:
    branches:
      - main
      - angular-material

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
        image: node:20
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - name: Build
        run: npm run build
      - name: Get SSH Key and set permission
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github-actions-created-on-lightsail
            chmod 600 ~/.ssh/github-actions-created-on-lightsail
      - name: Deploy using SCP
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/github-actions-created-on-lightsail ./dist/apps/mg-frontend/browser/* ubuntu@52.28.37.136:/var/www/mygifts-frontend
